// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UntitledTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void untitled() {
    driver.get("https://sravni.bet/");
    driver.manage().window().setSize(new Dimension(1536, 798));
    driver.findElement(By.cssSelector(".style-module-scss-module___5I0Dq__container:nth-child(2) .style-module-scss-module___5I0Dq__team:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_1pt5x8j:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".style-module-scss-module___5I0Dq__container:nth-child(1) .style-module-scss-module__xVTBhW__link > .\\_10cf6rv")).click();
    driver.findElement(By.cssSelector(".style-module-scss-module__8SV72W__tag:nth-child(2) .\\_1oic697")).click();
    driver.findElement(By.cssSelector(".h-mt-32")).click();
    driver.findElement(By.cssSelector(".style-module-scss-module__8SV72W__tag:nth-child(3) .\\_1oic697")).click();
    driver.findElement(By.cssSelector(".style-module-scss-module__8SV72W__tag:nth-child(4) .\\_1oic697")).click();
    driver.findElement(By.cssSelector(".style-module-scss-module__8SV72W__tag:nth-child(1) .\\_1oic697")).click();
    driver.findElement(By.cssSelector(".style-module-scss-module___5I0Dq__container:nth-child(1) .style-module-scss-module__z-1r6q__tournamentDate")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".style-module-scss-module__inVsMG__betCard:nth-child(3) > .style-module-scss-module__inVsMG__betCardTitle")).click();
    vars.put("win2124", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win2124").toString());
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector("tr:nth-child(1) > .style-module-scss-module__q21c5G__center .\\_1ya60sh")).click();
    vars.put("win9755", waitForWindow(2000));
    driver.switchTo().window(vars.get("win9755").toString());
    driver.switchTo().window(vars.get("root").toString());
  }
}
